# Site settings
title: "Kyle Baley :: The Coding Hillbilly"
email: kyle@baley.org
description: > # this means to ignore newlines until "baseurl:"
  "We're stuck with technology when what we really want is just stuff that works" - Douglas Adams
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kyle.baley.org" # the base hostname & protocol for your site
twitter_username: kyle_baley
github_username:  kbaley

# Build settings
markdown: kramdown

permalink: 	/:year/:month/:title
